stages:
  download_dataset:
    cmd: ssh mlops@130.193.53.150 && scp ~/bot/big_bot_config.json && python3 scripts/data_proc/load_process_data.py
    
    deps:
    - bot/big_bot_config.json
    - scripts/data_proc/load_process_data.py

    outs:
    - 



